package com.vivenotes.byteink.upstream

import java.io.File
import java.security.MessageDigest
import java.util.SortedSet
import java.util.zip.ZipFile

/**
 * The JNI surface of an AndroidX Ink release, read from its published JVM artifacts:
 *
 * - [natives]: the JNI names of every native method the jars declare, which any `libink` loaded
 *   under them has to export;
 * - [exports]: the `Java_*` functions Google's own `linux-x86_64/libink.so` (shipped in
 *   ink-nativeloader-jvm) exports, which is the whole JNI surface of the google/ink commit it was
 *   built from, Android-only functions included.
 */
internal class Surface(
    val version: String,
    val jarNames: List<String>,
    val natives: SortedSet<String>,
    val exports: SortedSet<String>,
    val binarySha256: String,
) {
    fun nativesText(): String = SymbolList.render(
        listOf(
            "JNI natives declared by the AndroidX Ink $version JVM artifacts:",
            "  ${jarNames.joinToString(", ")}",
            "A native library loaded by them must export every symbol below.",
            "Generated by ./gradlew :upstream:jniSurface; do not edit.",
        ),
        natives,
    )

    fun exportsText(): String = SymbolList.render(
        listOf(
            "Java_* functions exported by Google's $LINUX_BINARY in ink-nativeloader-jvm-$version.jar",
            "(sha256 $binarySha256): the JNI surface of the google/ink commit it was built from.",
            "Generated by ./gradlew :upstream:jniSurface; do not edit.",
        ),
        exports,
    )

    companion object {
        const val LINUX_BINARY = "linux-x86_64/libink.so"

        fun read(version: String, jars: List<File>): Surface {
            require(jars.isNotEmpty()) { "No jars given" }
            val natives = JniNames.of(jars.flatMap(JarNatives::read))
            val loader = jars.singleOrNull { it.name.startsWith("ink-nativeloader-jvm") }
                ?: throw IllegalArgumentException("ink-nativeloader-jvm is not among the jars")
            val binary = ZipFile(loader).use { zip ->
                val entry = zip.getEntry(LINUX_BINARY)
                    ?: throw IllegalArgumentException("${loader.name} has no $LINUX_BINARY")
                zip.getInputStream(entry).use { it.readBytes() }
            }
            val exports = ElfExports.functions(binary).filterTo(sortedSetOf()) { it.startsWith("Java_") }
            val digest = MessageDigest.getInstance("SHA-256").digest(binary)
            return Surface(
                version = version,
                jarNames = jars.map { it.name.removeSuffix(".jar").removeSuffix("-$version") }.sorted(),
                natives = natives,
                exports = exports,
                binarySha256 = digest.joinToString("") { "%02x".format(it) },
            )
        }
    }
}

/** `surface`: writes upstream/jni/ from the jars, or with `--check` fails if it no longer matches. */
internal fun surfaceCommand(arguments: Arguments): Int {
    val surface = Surface.read(arguments.required("--version"), arguments.all("--jar").map(::File))
    val unexported = surface.natives - surface.exports
    if (unexported.isNotEmpty()) {
        throw CheckFailed(
            "Google's ${Surface.LINUX_BINARY} does not export ${unexported.size} natives the jars " +
                "declare:\n${unexported.joinToString("\n") { "  $it" }}",
        )
    }
    val files = listOf(
        File(arguments.required("--natives")) to surface.nativesText(),
        File(arguments.required("--exports")) to surface.exportsText(),
    )
    if (!arguments.flag("--check")) {
        files.forEach { (file, text) ->
            file.parentFile?.mkdirs()
            file.writeText(text)
        }
        println("${surface.natives.size} natives, ${surface.exports.size} exports (Google's binary sha256 ${surface.binarySha256})")
        return 0
    }
    val stale = files.mapNotNull { (file, text) ->
        when {
            !file.isFile -> "$file does not exist"
            file.readText() == text -> null
            else -> {
                // "missing" and "unexpected" describe the checked-in file against the jars.
                val change = SymbolList.difference(expected = SymbolList.parse(text), actual = SymbolList.read(file))
                "$file is out of date" + (change?.let { ":\n$it" } ?: " (its header differs)")
            }
        }
    }
    if (stale.isNotEmpty()) {
        throw CheckFailed(
            stale.joinToString("\n") + "\nRegenerate with ./gradlew :upstream:jniSurface and review the change.",
        )
    }
    return 0
}
